name: Test API

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run tests
        run: newman run gudang-api.postman_collection.json -e gudang-api-env.postman_environment.json
