name: Test API

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Newman
        run: npm install -g newman

      - name: Run tests
        id: test
        run: newman run gudang-api.postman_collection.json -e gudang-api-env.postman_environment.json || echo "::set-output name=exit_code::1"

      - name: Commit changes
        if: ${{ steps.test.outputs.exit_code != '1' }}
        run: |
          git config --global user.name "Your Name"
          git config --global user.email "youremail@example.com"
          git add .
          git commit -m "Test results"
          git push